export const GET_ITEM_FROM_DATABASE = 'GET_ITEM_FROM_DATABASE'
export const ADD_ITEM_TO_DATABASE = 'ADD_ITEM_TO_DATABASE'
export const CHANGE_ITEM_FROM_DATABASE = 'CHANGE_ITEM_FROM_DATABASE'
export const REMOVE_ITEM_FROM_DATABASE = 'REMOVE_ITEM_FROM_DATABASE'